/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

int triang(int Side1, int Side2, int Side3)
 {
   int __retres;
   int triOut;
   pc_label((Side1 <= 0 || Side2 <= 0) || Side3 <= 0,2,"DC");
   pc_label(! ((Side1 <= 0 || Side2 <= 0) || Side3 <= 0),1,"DC");
   if ((Side1 <= 0 || Side2 <= 0) || Side3 <= 0) {
     triOut = 4;
     __retres = triOut;
     goto return_label;
   }
   triOut = 0;
   pc_label(Side1 == Side2,4,"DC");
   pc_label(! (Side1 == Side2),3,"DC");
   if (Side1 == Side2) triOut ++;
   pc_label(Side1 == Side3,6,"DC");
   pc_label(! (Side1 == Side3),5,"DC");
   if (Side1 == Side3) triOut += 2;
   pc_label(Side2 == Side3,8,"DC");
   pc_label(! (Side2 == Side3),7,"DC");
   if (Side2 == Side3) triOut += 3;
   pc_label(triOut == 0,10,"DC");
   pc_label(! (triOut == 0),9,"DC");
   if (triOut == 0) {
     pc_label((Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2,
              12,"DC");
     pc_label(! ((Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || 
                 Side1 + Side3 <= Side2),11,"DC");
     if ((Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2) 
       triOut = 4;
     else triOut = 1;
     __retres = triOut;
     goto return_label;
   }
   pc_label(triOut > 3,14,"DC");
   pc_label(! (triOut > 3),13,"DC");
   if (triOut > 3) triOut = 3;
   else {
     pc_label(triOut == 1 && Side1 + Side2 > Side3,16,"DC");
     pc_label(! (triOut == 1 && Side1 + Side2 > Side3),15,"DC");
     if (triOut == 1 && Side1 + Side2 > Side3) triOut = 2;
     else {
       pc_label(triOut == 2 && Side1 + Side3 > Side2,18,"DC");
       pc_label(! (triOut == 2 && Side1 + Side3 > Side2),17,"DC");
       if (triOut == 2 && Side1 + Side3 > Side2) triOut = 2;
       else {
         pc_label(triOut == 3 && Side2 + Side3 > Side1,20,"DC");
         pc_label(! (triOut == 3 && Side2 + Side3 > Side1),19,"DC");
         if (triOut == 3 && Side2 + Side3 > Side1) triOut = 2;
         else triOut = 4;
       }
     }
   }
   __retres = triOut;
   return_label: return __retres;
 }


