/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

int triang(int Side1, int Side2, int Side3)
 {
   int __retres;
   int triOut;
   pc_label(Side1 <= 0,1,"CC");
   pc_label(! (Side1 <= 0),2,"CC");
   pc_label(Side2 <= 0,3,"CC");
   pc_label(! (Side2 <= 0),4,"CC");
   pc_label(Side3 <= 0,5,"CC");
   pc_label(! (Side3 <= 0),6,"CC");
   if ((Side1 <= 0 || Side2 <= 0) || Side3 <= 0) {
     triOut = 4;
     __retres = triOut;
     goto return_label;
   }
   triOut = 0;
   pc_label(Side1 == Side2,7,"CC");
   pc_label(! (Side1 == Side2),8,"CC");
   if (Side1 == Side2) triOut ++;
   pc_label(Side1 == Side3,9,"CC");
   pc_label(! (Side1 == Side3),10,"CC");
   if (Side1 == Side3) triOut += 2;
   pc_label(Side2 == Side3,11,"CC");
   pc_label(! (Side2 == Side3),12,"CC");
   if (Side2 == Side3) triOut += 3;
   pc_label(triOut == 0,13,"CC");
   pc_label(! (triOut == 0),14,"CC");
   if (triOut == 0) {
     pc_label(Side1 + Side2 <= Side3,15,"CC");
     pc_label(! (Side1 + Side2 <= Side3),16,"CC");
     pc_label(Side2 + Side3 <= Side1,17,"CC");
     pc_label(! (Side2 + Side3 <= Side1),18,"CC");
     pc_label(Side1 + Side3 <= Side2,19,"CC");
     pc_label(! (Side1 + Side3 <= Side2),20,"CC");
     if ((Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2) 
       triOut = 4;
     else triOut = 1;
     __retres = triOut;
     goto return_label;
   }
   pc_label(triOut > 3,21,"CC");
   pc_label(! (triOut > 3),22,"CC");
   if (triOut > 3) triOut = 3;
   else {
     pc_label(triOut == 1,23,"CC");
     pc_label(! (triOut == 1),24,"CC");
     pc_label(Side1 + Side2 > Side3,25,"CC");
     pc_label(! (Side1 + Side2 > Side3),26,"CC");
     if (triOut == 1 && Side1 + Side2 > Side3) triOut = 2;
     else {
       pc_label(triOut == 2,27,"CC");
       pc_label(! (triOut == 2),28,"CC");
       pc_label(Side1 + Side3 > Side2,29,"CC");
       pc_label(! (Side1 + Side3 > Side2),30,"CC");
       if (triOut == 2 && Side1 + Side3 > Side2) triOut = 2;
       else {
         pc_label(triOut == 3,31,"CC");
         pc_label(! (triOut == 3),32,"CC");
         pc_label(Side2 + Side3 > Side1,33,"CC");
         pc_label(! (Side2 + Side3 > Side1),34,"CC");
         if (triOut == 3 && Side2 + Side3 > Side1) triOut = 2;
         else triOut = 4;
       }
     }
   }
   __retres = triOut;
   return_label: return __retres;
 }


