/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

int triang(int Side1, int Side2, int Side3)
 {
   int __retres;
   int triOut;
   pc_label(Side1 <= 0 && Side2 <= 0,1,"NCC");
   pc_label(Side1 <= 0 && ! (Side2 <= 0),2,"NCC");
   pc_label(! (Side1 <= 0) && Side2 <= 0,3,"NCC");
   pc_label(! (Side1 <= 0) && ! (Side2 <= 0),4,"NCC");
   pc_label(Side1 <= 0 && Side3 <= 0,5,"NCC");
   pc_label(Side1 <= 0 && ! (Side3 <= 0),6,"NCC");
   pc_label(! (Side1 <= 0) && Side3 <= 0,7,"NCC");
   pc_label(! (Side1 <= 0) && ! (Side3 <= 0),8,"NCC");
   pc_label(Side2 <= 0 && Side3 <= 0,9,"NCC");
   pc_label(Side2 <= 0 && ! (Side3 <= 0),10,"NCC");
   pc_label(! (Side2 <= 0) && Side3 <= 0,11,"NCC");
   pc_label(! (Side2 <= 0) && ! (Side3 <= 0),12,"NCC");
   if ((Side1 <= 0 || Side2 <= 0) || Side3 <= 0) {
     triOut = 4;
     __retres = triOut;
     goto return_label;
   }
   triOut = 0;
   pc_label(Side1 == Side2,13,"NCC");
   pc_label(! (Side1 == Side2),14,"NCC");
   if (Side1 == Side2) triOut ++;
   pc_label(Side1 == Side3,15,"NCC");
   pc_label(! (Side1 == Side3),16,"NCC");
   if (Side1 == Side3) triOut += 2;
   pc_label(Side2 == Side3,17,"NCC");
   pc_label(! (Side2 == Side3),18,"NCC");
   if (Side2 == Side3) triOut += 3;
   pc_label(triOut == 0,19,"NCC");
   pc_label(! (triOut == 0),20,"NCC");
   if (triOut == 0) {
     pc_label(Side1 + Side2 <= Side3 && Side2 + Side3 <= Side1,21,"NCC");
     pc_label(Side1 + Side2 <= Side3 && ! (Side2 + Side3 <= Side1),22,"NCC");
     pc_label(! (Side1 + Side2 <= Side3) && Side2 + Side3 <= Side1,23,"NCC");
     pc_label(! (Side1 + Side2 <= Side3) && ! (Side2 + Side3 <= Side1),24,
              "NCC");
     pc_label(Side1 + Side2 <= Side3 && Side1 + Side3 <= Side2,25,"NCC");
     pc_label(Side1 + Side2 <= Side3 && ! (Side1 + Side3 <= Side2),26,"NCC");
     pc_label(! (Side1 + Side2 <= Side3) && Side1 + Side3 <= Side2,27,"NCC");
     pc_label(! (Side1 + Side2 <= Side3) && ! (Side1 + Side3 <= Side2),28,
              "NCC");
     pc_label(Side2 + Side3 <= Side1 && Side1 + Side3 <= Side2,29,"NCC");
     pc_label(Side2 + Side3 <= Side1 && ! (Side1 + Side3 <= Side2),30,"NCC");
     pc_label(! (Side2 + Side3 <= Side1) && Side1 + Side3 <= Side2,31,"NCC");
     pc_label(! (Side2 + Side3 <= Side1) && ! (Side1 + Side3 <= Side2),32,
              "NCC");
     if ((Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2) 
       triOut = 4;
     else triOut = 1;
     __retres = triOut;
     goto return_label;
   }
   pc_label(triOut > 3,33,"NCC");
   pc_label(! (triOut > 3),34,"NCC");
   if (triOut > 3) triOut = 3;
   else {
     pc_label(triOut == 1 && Side1 + Side2 > Side3,35,"NCC");
     pc_label(triOut == 1 && ! (Side1 + Side2 > Side3),36,"NCC");
     pc_label(! (triOut == 1) && Side1 + Side2 > Side3,37,"NCC");
     pc_label(! (triOut == 1) && ! (Side1 + Side2 > Side3),38,"NCC");
     if (triOut == 1 && Side1 + Side2 > Side3) triOut = 2;
     else {
       pc_label(triOut == 2 && Side1 + Side3 > Side2,39,"NCC");
       pc_label(triOut == 2 && ! (Side1 + Side3 > Side2),40,"NCC");
       pc_label(! (triOut == 2) && Side1 + Side3 > Side2,41,"NCC");
       pc_label(! (triOut == 2) && ! (Side1 + Side3 > Side2),42,"NCC");
       if (triOut == 2 && Side1 + Side3 > Side2) triOut = 2;
       else {
         pc_label(triOut == 3 && Side2 + Side3 > Side1,43,"NCC");
         pc_label(triOut == 3 && ! (Side2 + Side3 > Side1),44,"NCC");
         pc_label(! (triOut == 3) && Side2 + Side3 > Side1,45,"NCC");
         pc_label(! (triOut == 3) && ! (Side2 + Side3 > Side1),46,"NCC");
         if (triOut == 3 && Side2 + Side3 > Side1) triOut = 2;
         else triOut = 4;
       }
     }
   }
   __retres = triOut;
   return_label: return __retres;
 }


