/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

int main(int a, int b)
 {
   int __retres;
   pc_label(a * b != a + b,1,"WM AOR");
   pc_label(a / b != a + b,2,"WM AOR");
   pc_label(a - b != a + b,3,"WM AOR");
   pc_label(a < 0,4,"WM ABS");
   pc_label(b < 0,5,"WM ABS");
   __retres = a + b;
   pc_label(__retres < 0,6,"WM ABS");
   return __retres;
 }


