/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

int main(int a, int b, int c)
 {
   int __retres;
   pc_label(! ((a & b) != 0LL),1,"ASSERT");
   /*@ assert (a & b) ≢ 0; */ ;
   if (c) {
     __retres = 0;
     goto return_label;
   }
   __retres = 1;
   return_label: return __retres;
 }


