/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

int main(int a, int b)
 {
   int __retres;
   pc_label((a < b || a / b != 42) != (a < b && a / b != 42),11,"WM COR");
   pc_label((a <= b) != (a < b),12,"WM ROR");
   pc_label((a > b) != (a < b),13,"WM ROR");
   pc_label((a >= b) != (a < b),14,"WM ROR");
   pc_label(a < 0,15,"WM ABS");
   pc_label(b < 0,16,"WM ABS");
   pc_label((a / b == 42) != (a / b != 42),17,"WM ROR");
   pc_label(a * b != a / b,18,"WM AOR");
   pc_label(a + b != a / b,19,"WM AOR");
   pc_label(a - b != a / b,20,"WM AOR");
   pc_label(a < 0,21,"WM ABS");
   pc_label(b < 0,22,"WM ABS");
   if (a < b && a / b != 42) {
     pc_label(a < 0,1,"WM ABS");
     pc_label(b < 0,2,"WM ABS");
     __retres = a % b;
     goto return_label;
   }
   else {
     pc_label((a + b) / 4 != (a + b) * 4,3,"WM AOR");
     pc_label((a + b) + 4 != (a + b) * 4,4,"WM AOR");
     pc_label((a + b) - 4 != (a + b) * 4,5,"WM AOR");
     pc_label(a * b != a + b,6,"WM AOR");
     pc_label(a / b != a + b,7,"WM AOR");
     pc_label(a - b != a + b,8,"WM AOR");
     pc_label(a < 0,9,"WM ABS");
     pc_label(b < 0,10,"WM ABS");
     __retres = (a + b) * 4;
     goto return_label;
   }
   pc_label(__retres < 0,23,"WM ABS");
   return_label: return __retres;
 }


