/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif

#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int f(void)
 {
   int __retres;
   __retres = 0;
   return __retres;
 }

int maintest(int c)
{
  int __retres;
  pc_label_sequence(1,1435UL,1,2,"49",0);
  pc_label_sequence(1,1381UL,1,2,"49",0);
  pc_label_sequence(1,1328UL,1,2,"49",0);
  pc_label_sequence(1,1276UL,1,2,"49",0);
  pc_label_sequence_condition(0,"50");
  int a = 1;
  pc_label_sequence(1,1434UL,1,2,"50",0);
  pc_label_sequence(1,1380UL,1,2,"50",0);
  pc_label_sequence(1,1327UL,1,2,"50",0);
  pc_label_sequence_condition(0,"51");
  int b = 2;
  pc_label_sequence(1,1488UL,1,2,"51",0);
  pc_label_sequence(1,1433UL,1,2,"51",0);
  pc_label_sequence(1,1379UL,1,2,"51",0);
  test: ;
  pc_label_sequence(1,1327UL,2,2,"50",0);
  if (a) {
    pc_label_sequence(1,1379UL,2,2,"51",0);
    if (b) {
      pc_label_sequence_condition(0,"51");
      b = 3;
      pc_label_sequence(1,1601UL,1,2,"51",0);
      pc_label_sequence(1,1544UL,1,2,"51",0);
    }
    else {
      test2: pc_label_sequence_condition(0,"50");
             a = f();
      pc_label_sequence(1,1545UL,1,2,"50",0);
      pc_label_sequence(1,1489UL,1,2,"50",0);
    }
  }
  else {
    pc_label_sequence(1,1489UL,2,2,"50",0);
    pc_label_sequence(1,1380UL,2,2,"50",0);
    pc_label_sequence_condition(0,"52");
    int i = a;
    pc_label_sequence(1,1487UL,1,2,"52",0);
    pc_label_sequence(1,1432UL,1,2,"52",0);
    while (1) {
      pc_label_sequence(1,1544UL,2,2,"51",0);
      pc_label_sequence(1,1433UL,2,2,"51",0);
      pc_label_sequence(1,1654UL,2,2,"52",0);
      pc_label_sequence(1,1432UL,2,2,"52",0);
      if (! (i < b)) break;
      f();
      pc_label_sequence(1,1713UL,2,2,"52",0);
      pc_label_sequence(1,1487UL,2,2,"52",0);
      pc_label_sequence_condition(0,"52");
      i ++;
      pc_label_sequence(1,1713UL,1,2,"52",0);
      pc_label_sequence(1,1654UL,1,2,"52",0);
    }
  }
  test4: ;
  pc_label_sequence(1,1276UL,2,2,"49",0);
  switch (c) {
    int tmp;
    test5: case 1: case 14: ;
    pc_label_sequence(1,1601UL,2,2,"51",0);
    pc_label_sequence(1,1488UL,2,2,"51",0);
    pc_label_sequence(1,1545UL,2,2,"50",0);
    pc_label_sequence(1,1434UL,2,2,"50",0);
    __retres = a + b;
    goto return_label;
    case 12: case 13: ;
    pc_label_sequence(1,1328UL,2,2,"49",0);
    __retres = c;
    goto return_label;
    default: ;
    pc_label_sequence(1,1381UL,2,2,"49",0);
    if (c) tmp = 0;
    else {
      pc_label_sequence(1,1435UL,2,2,"49",0);
      tmp = c;
    }
    __retres = tmp;
    goto return_label;
  }
  __retres = 0;
  return_label: return __retres;
}


