/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif

int my_strcmp(char const *s1, char const *s2)
 {
   int __retres;
   pc_label(s1 == s2,1,"GACC");
   pc_label(! (s1 == s2),2,"GACC");
   if (s1 == s2) {
     __retres = 0;
     goto return_label;
   }
   while (1) {
     char const *tmp_0;
     char const *tmp;
     {
       /*sequence*/
       tmp_0 = s2;
       s2 ++;
       ;
     }
     pc_label((int)*s1 == (int)*tmp_0,3,"GACC");
     pc_label(! ((int)*s1 == (int)*tmp_0),4,"GACC");
     if (! ((int)*s1 == (int)*tmp_0)) break;
     {
       /*sequence*/
       tmp = s1;
       s1 ++;
       ;
     }
     pc_label((int)*tmp == 0,5,"GACC");
     pc_label(! ((int)*tmp == 0),6,"GACC");
     if ((int)*tmp == '\000') {
       __retres = 0;
       goto return_label;
     }
   }
   {
     /*sequence*/
     s2 --;
     ;
   }
   __retres = (int)*((unsigned char *)s1) - (int)*((unsigned char *)s2);
   return_label: return __retres;
 }

int search(char *keyName, char **base, int nmemb)
{
  int __retres;
  __retres = 1;
  return __retres;
}

void gdImageStringFTEx(char *string, int nondetEntry)
{
  int next;
  int encoding;
  int i;
  int ch;
  int len;
  int byte;
  encoding = nondetEntry;
  pc_label(encoding > 2 && ! (encoding < 0),7,"GACC");
  pc_label(! (encoding > 2) && ! (encoding < 0),8,"GACC");
  pc_label(encoding < 0 && ! (encoding > 2),9,"GACC");
  pc_label(! (encoding < 0) && ! (encoding > 2),10,"GACC");
  if (encoding > 2 || encoding < 0) goto return_label;
  next = 0;
  i = 0;
  while (1) {
    pc_label((int)*(string + next) != 0,11,"GACC");
    pc_label(! ((int)*(string + next) != 0),12,"GACC");
    if (! ((int)*(string + next) != 0)) break;
    ch = (int)*(string + next);
    pc_label(ch == 13,13,"GACC");
    pc_label(! (ch == 13),14,"GACC");
    if (ch == '\r') {
      next ++;
      goto __Cont;
    }
    pc_label(ch == 10,15,"GACC");
    pc_label(! (ch == 10),16,"GACC");
    if (ch == '\n') {
      next ++;
      goto __Cont;
    }
    switch (encoding) {
      case 0:
        {
          char *p;
          int indiceP;
          char entity_name_buf[8 + 1];
          char *key;
          int ii;
          int n;
          int res;
          char *entities[3];
          indiceP = 0;
          n = 0;
          res = 0;
          entities[0] = (char *)"AElig";
          entities[1] = (char *)"Aacute";
          entities[2] = (char *)"Acirc";
          byte = (int)((unsigned char)*(string + next));
          pc_label(byte == 38,17,"GACC");
          pc_label(! (byte == 38),18,"GACC");
          if (byte == '&') {
            byte = (int)((unsigned char)*(string + (next + 1)));
            pc_label(byte == 35,19,"GACC");
            pc_label(! (byte == 35),20,"GACC");
            if (byte == '#') {
              byte = (int)((unsigned char)*(string + (next + 2)));
              pc_label(byte == 120 && ! (byte == 88),21,"GACC");
              pc_label(! (byte == 120) && ! (byte == 88),22,"GACC");
              pc_label(byte == 88 && ! (byte == 120),23,"GACC");
              pc_label(! (byte == 88) && ! (byte == 120),24,"GACC");
              if (byte == 'x' || byte == 'X') {
                ii = 3;
                while (1) {
                  pc_label(ii < 8,25,"GACC");
                  pc_label(! (ii < 8),26,"GACC");
                  if (! (ii < 8)) break;
                  byte = (int)((unsigned char)*(string + (next + ii)));
                  pc_label(byte >= 65 && byte <= 70,27,"GACC");
                  pc_label(! (byte >= 65) && byte <= 70,28,"GACC");
                  pc_label(byte <= 70 && byte >= 65,29,"GACC");
                  pc_label(! (byte <= 70) && byte >= 65,30,"GACC");
                  if (byte >= 'A' && byte <= 'F') byte = (byte - 'A') + 10;
                  else {
                    pc_label(byte >= 97 && byte <= 102,31,"GACC");
                    pc_label(! (byte >= 97) && byte <= 102,32,"GACC");
                    pc_label(byte <= 102 && byte >= 97,33,"GACC");
                    pc_label(! (byte <= 102) && byte >= 97,34,"GACC");
                    if (byte >= 'a' && byte <= 'f') byte = (byte - 'a') + 10;
                    else {
                      pc_label(byte >= 48 && byte <= 57,35,"GACC");
                      pc_label(! (byte >= 48) && byte <= 57,36,"GACC");
                      pc_label(byte <= 57 && byte >= 48,37,"GACC");
                      pc_label(! (byte <= 57) && byte >= 48,38,"GACC");
                      if (byte >= '0' && byte <= '9') byte -= '0';
                      else break;
                    }
                  }
                  n = n * 16 + byte;
                  ii ++;
                }
              }
              else {
                ii = 2;
                while (1) {
                  pc_label(ii < 8,39,"GACC");
                  pc_label(! (ii < 8),40,"GACC");
                  if (! (ii < 8)) break;
                  byte = (int)((unsigned char)*(string + (next + ii)));
                  pc_label(byte >= 48 && byte <= 57,41,"GACC");
                  pc_label(! (byte >= 48) && byte <= 57,42,"GACC");
                  pc_label(byte <= 57 && byte >= 48,43,"GACC");
                  pc_label(! (byte <= 57) && byte >= 48,44,"GACC");
                  if (byte >= '0' && byte <= '9') n = n * 10 + (byte - '0');
                  else break;
                  ii ++;
                }
              }
              pc_label(byte == 59,45,"GACC");
              pc_label(! (byte == 59),46,"GACC");
              if (byte == ';') {
                {
                  /*sequence*/
                  ii ++;
                  len = ii;
                }
                goto endFun;
              }
            }
            else {
              {
                /*sequence*/
                p = entity_name_buf;
                key = p;
              }
              ii = 1;
              while (1) {
                pc_label(ii < 9,47,"GACC");
                pc_label(! (ii < 9),48,"GACC");
                if (! (ii < 1 + 8)) break;
                byte = (int)((unsigned char)*(string + (next + ii)));
                pc_label(byte == 0,49,"GACC");
                pc_label(! (byte == 0),50,"GACC");
                if (byte == 0) break;
                pc_label(byte == 59,51,"GACC");
                pc_label(! (byte == 59),52,"GACC");
                if (byte == ';') {
                  *(p + indiceP) = (char)0;
                  indiceP ++;
                  res = search(key,entities,3);
                  pc_label(res != 0,53,"GACC");
                  pc_label(! (res != 0),54,"GACC");
                  if (res != 0) {
                    {
                      /*sequence*/
                      ii ++;
                      len = ii;
                    }
                    goto endFun;
                  }
                  break;
                }
                *(p + indiceP) = (char)byte;
                indiceP ++;
                ii ++;
              }
            }
          }
          len = 1;
          byte = (int)((unsigned char)*(string + next));
          pc_label(byte < 0xC0,55,"GACC");
          pc_label(! (byte < 0xC0),56,"GACC");
          if (byte < 0xC0) len = 1;
          else {
            pc_label(byte < 0xE0,57,"GACC");
            pc_label(! (byte < 0xE0),58,"GACC");
            if (byte < 0xE0) {
              pc_label(((int)*(string + (next + 1)) & 0xC0) == 0x80,59,
                       "GACC");
              pc_label(! (((int)*(string + (next + 1)) & 0xC0) == 0x80),60,
                       "GACC");
              if (((int)*(string + (next + 1)) & 0xC0) == 0x80) len = 2;
              len = 1;
            }
            else {
              pc_label(byte < 0xF0,61,"GACC");
              pc_label(! (byte < 0xF0),62,"GACC");
              if (byte < 0xF0) {
                pc_label(((int)*(string + (next + 1)) & 0xC0) == 0x80 && 
                         ((int)*(string + (next + 2)) & 0xC0) == 0x80,63,
                         "GACC");
                pc_label(! (((int)*(string + (next + 1)) & 0xC0) == 0x80) && 
                         ((int)*(string + (next + 2)) & 0xC0) == 0x80,64,
                         "GACC");
                pc_label(((int)*(string + (next + 2)) & 0xC0) == 0x80 && 
                         ((int)*(string + (next + 1)) & 0xC0) == 0x80,65,
                         "GACC");
                pc_label(! (((int)*(string + (next + 2)) & 0xC0) == 0x80) && 
                         ((int)*(string + (next + 1)) & 0xC0) == 0x80,66,
                         "GACC");
                if (((int)*(string + (next + 1)) & 0xC0) == 0x80 && (
                                                                    (int)*(
                                                                    string + (
                                                                    next + 2)) & 0xC0) == 0x80) 
                  len = 3;
                len = 1;
              }
            }
          }
          endFun: next += len;
        }
      break;
      case 1:
        {
          unsigned char c;
          c = (unsigned char)*(string + next);
          pc_label(0xA1 <= (int)c && (int)c <= 0xFE,67,"GACC");
          pc_label(! (0xA1 <= (int)c) && (int)c <= 0xFE,68,"GACC");
          pc_label((int)c <= 0xFE && 0xA1 <= (int)c,69,"GACC");
          pc_label(! ((int)c <= 0xFE) && 0xA1 <= (int)c,70,"GACC");
          if (0xA1 <= (int)c && (int)c <= 0xFE) next ++;
          pc_label((int)*(string + next) != 0,71,"GACC");
          pc_label(! ((int)*(string + next) != 0),72,"GACC");
          if ((int)*(string + next) != 0) next ++;
        }
      break;
      case 2:
        ch = (int)*(string + next) & 0xFF;
        next ++;
        pc_label(ch >= 161 && (int)*(string + next) != 0,73,"GACC");
        pc_label(! (ch >= 161) && (int)*(string + next) != 0,74,"GACC");
        pc_label((int)*(string + next) != 0 && ch >= 161,75,"GACC");
        pc_label(! ((int)*(string + next) != 0) && ch >= 161,76,"GACC");
        if (ch >= 161 && (int)*(string + next) != 0) next ++;
      break;
    }
    __Cont: i ++;
  }
  return_label: return;
}


