/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

void donothing(void)
 {
   return;
 }

int maintest(int i)
{
  int __retres;
  int __SEQ_STATUS_1 = 1;
  while (1) __SEQ_STATUS_1 = 0;
  pc_label(__SEQ_STATUS_1 == 1,1,"SLO");
  int __SEQ_STATUS_2 = 1;
  while (1) {
    __SEQ_STATUS_2 = 0;
    donothing();
  }
  pc_label(__SEQ_STATUS_2 == 1,2,"SLO");
  int __SEQ_STATUS_3 = 1;
  while (1) {
    __SEQ_STATUS_3 = 0;
    if (! (i < 10)) break;
  }
  pc_label(__SEQ_STATUS_3 == 1,3,"SLO");
  int __SEQ_STATUS_4 = 1;
  while (1) {
    if (i < 10) __SEQ_STATUS_4 = 0; else break;
    donothing();
  }
  pc_label(__SEQ_STATUS_4 == 1,4,"SLO");
  int __SEQ_STATUS_5 = 1;
  while (1) {
    int tmp;
    __SEQ_STATUS_5 = 0;
    tmp = i;
    i ++;
    ;
    if (! tmp) break;
  }
  pc_label(__SEQ_STATUS_5 == 1,5,"SLO");
  int __SEQ_STATUS_6 = 1;
  while (1) {
    int tmp_0;
    tmp_0 = i;
    i ++;
    ;
    if (tmp_0) __SEQ_STATUS_6 = 0; else break;
    donothing();
  }
  pc_label(__SEQ_STATUS_6 == 1,6,"SLO");
  int __SEQ_STATUS_7 = 1;
  while (1) __SEQ_STATUS_7 = 0;
  pc_label(__SEQ_STATUS_7 == 1,7,"SLO");
  int __SEQ_STATUS_8 = 1;
  while (1) {
    __SEQ_STATUS_8 = 0;
    donothing();
  }
  pc_label(__SEQ_STATUS_8 == 1,8,"SLO");
  int __SEQ_STATUS_9 = 1;
  while (1) {
    __SEQ_STATUS_9 = 0;
    if (! (i < 10)) break;
  }
  pc_label(__SEQ_STATUS_9 == 1,9,"SLO");
  int __SEQ_STATUS_10 = 1;
  while (1) {
    __SEQ_STATUS_10 = 0;
    donothing();
    if (! (i < 10)) break;
  }
  pc_label(__SEQ_STATUS_10 == 1,10,"SLO");
  int __SEQ_STATUS_11 = 1;
  while (1) {
    int tmp_1;
    __SEQ_STATUS_11 = 0;
    tmp_1 = i;
    i ++;
    ;
    if (! tmp_1) break;
  }
  pc_label(__SEQ_STATUS_11 == 1,11,"SLO");
  int __SEQ_STATUS_12 = 1;
  while (1) {
    int tmp_2;
    __SEQ_STATUS_12 = 0;
    donothing();
    tmp_2 = i;
    i ++;
    ;
    if (! tmp_2) break;
  }
  pc_label(__SEQ_STATUS_12 == 1,12,"SLO");
  __retres = 0;
  return __retres;
}


