/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

#define MAX_MUTATION 1
unsigned int cpt_mutation = 0;

/*@ assigns cpt_mutation;
    behavior can_mutate:
        assumes cpt_mutation < MAX_MUTATION;
        ensures  \result <==> cpt_mutation == \at(cpt_mutation, Pre) + 1;
        ensures !\result <==> cpt_mutation == \at(cpt_mutation, Pre);

    behavior cant_mutate:
        assumes cpt_mutation >= MAX_MUTATION;
        ensures !\result;
        ensures cpt_mutation == \at(cpt_mutation, Pre);

    complete behaviors;
    disjoint behaviors;
*/
int mutate();

int f1(int password)
{
  int lannot_mut_2;
  int lannot_mut_1;
  int __retres;
  ;
  lannot_mut_1 = mutate();
  if (lannot_mut_1 && ! (password != 12345) || ! lannot_mut_1 && password != 12345) {
    __retres = 1;
    goto return_label;
  }
  lannot_mut_2 = mutate();
  if (lannot_mut_2 && ! (password != 12345) || ! lannot_mut_2 && password != 12345) {
    __retres = 1;
    goto return_label;
  }
  pc_label(lannot_mut_1 || lannot_mut_2,1,"RCC");
  __retres = 0;
  return_label: return __retres;
}

int f2(int password)
{
  int lannot_mut_4;
  int lannot_mut_3;
  int __retres;
  ;
  ;
  lannot_mut_3 = mutate();
  lannot_mut_4 = mutate();
  if ((lannot_mut_3 && ! (password != 12345) || ! lannot_mut_3 && password != 12345) || (
      lannot_mut_4 && ! (password != 12345) || ! lannot_mut_4 && password != 12345)) {
    __retres = 1;
    goto return_label;
  }
  pc_label(lannot_mut_3 || lannot_mut_4,2,"RCC");
  __retres = 0;
  return_label: return __retres;
}

int f3(int password)
{
  int lannot_mut_7;
  int lannot_mut_6;
  int lannot_mut_5;
  int __retres;
  ;
  lannot_mut_5 = mutate();
  if (lannot_mut_5 && ! (password == 12345) || ! lannot_mut_5 && password == 12345) {
    lannot_mut_6 = mutate();
    if (lannot_mut_6 && ! (password != 12345) || ! lannot_mut_6 && password != 12345) {
      __retres = 1;
      goto return_label;
    }
    pc_label(lannot_mut_5 || lannot_mut_6,3,"RCC");
    lannot_mut_7 = mutate();
    if (lannot_mut_7 && ! (password != 12345) || ! lannot_mut_7 && password != 12345) {
      __retres = 1;
      goto return_label;
    }
    pc_label(lannot_mut_5 || (lannot_mut_6 || lannot_mut_7),4,"RCC");
    __retres = 0;
    goto return_label;
  }
  __retres = 1;
  return_label: return __retres;
}

__inline static int check__fc_inline(int p1, int p2)
{
  int lannot_mut_8;
  int __retres;
  ;
  ;
  lannot_mut_8 = mutate();
  if (lannot_mut_8 && ! (p1 != p2) || ! lannot_mut_8 && p1 != p2) {
    __retres = 1;
    goto return_label;
  }
  pc_label(lannot_mut_8,5,"RCC");
  __retres = 0;
  goto return_label;
  ;
  return_label: return __retres;
}

int f4(int password)
{
  int lannot_mut_11;
  int lannot_mut_10;
  int lannot_mut_9;
  int __retres;
  int tmp;
  int tmp_0;
  int tmp_1;
  ;
  {
    int __retres_7;
    int p1 = password;
    int p2 = 12345;
    ;
    ;
    if (p1 != p2) {
      __retres_7 = 1;
      goto return_label_0;
    }
    ;
    __retres_7 = 0;
    goto return_label_0;
    ;
    return_label_0: tmp = __retres_7;
  }
  lannot_mut_9 = mutate();
  if (lannot_mut_9 && ! tmp || ! lannot_mut_9 && tmp) {
    __retres = 1;
    goto return_label;
  }
  {
    int __retres_10;
    int p1_8 = 12345;
    int p2_9 = password;
    ;
    ;
    if (p1_8 != p2_9) {
      __retres_10 = 1;
      goto return_label_1;
    }
    ;
    __retres_10 = 0;
    goto return_label_1;
    ;
    return_label_1: tmp_0 = __retres_10;
  }
  lannot_mut_10 = mutate();
  if (lannot_mut_10 && ! tmp_0 || ! lannot_mut_10 && tmp_0) {
    __retres = 1;
    goto return_label;
  }
  {
    int __retres_13;
    int p1_11 = password;
    int p2_12 = 12345;
    ;
    ;
    if (p1_11 != p2_12) {
      __retres_13 = 1;
      goto return_label_2;
    }
    ;
    __retres_13 = 0;
    goto return_label_2;
    ;
    return_label_2: tmp_1 = __retres_13;
  }
  lannot_mut_11 = mutate();
  if (lannot_mut_11 && ! tmp_1 || ! lannot_mut_11 && tmp_1) {
    __retres = 1;
    goto return_label;
  }
  pc_label(lannot_mut_9 || (lannot_mut_10 || lannot_mut_11),6,"RCC");
  __retres = 0;
  return_label: return __retres;
}


