/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif

int triang(int Side1, int Side2, int Side3)
 {
   int __retres;
   int triOut;
   pc_label(Side1 <= 0 && ! (Side2 <= 0 || Side3 <= 0),1,"GACC");
   pc_label(! (Side1 <= 0) && ! (Side2 <= 0 || Side3 <= 0),2,"GACC");
   pc_label(Side2 <= 0 && ! (Side1 <= 0 || Side3 <= 0),3,"GACC");
   pc_label(! (Side2 <= 0) && ! (Side1 <= 0 || Side3 <= 0),4,"GACC");
   pc_label(Side3 <= 0 && ! (Side1 <= 0 || Side2 <= 0),5,"GACC");
   pc_label(! (Side3 <= 0) && ! (Side1 <= 0 || Side2 <= 0),6,"GACC");
   if ((Side1 <= 0 || Side2 <= 0) || Side3 <= 0) {
     triOut = 4;
     __retres = triOut;
     goto return_label;
   }
   triOut = 0;
   pc_label(Side1 == Side2,7,"GACC");
   pc_label(! (Side1 == Side2),8,"GACC");
   if (Side1 == Side2) triOut ++;
   pc_label(Side1 == Side3,9,"GACC");
   pc_label(! (Side1 == Side3),10,"GACC");
   if (Side1 == Side3) triOut += 2;
   pc_label(Side2 == Side3,11,"GACC");
   pc_label(! (Side2 == Side3),12,"GACC");
   if (Side2 == Side3) triOut += 3;
   pc_label(triOut == 0,13,"GACC");
   pc_label(! (triOut == 0),14,"GACC");
   if (triOut == 0) {
     pc_label(Side1 + Side2 <= Side3 && ! (Side2 + Side3 <= Side1 || 
                                           Side1 + Side3 <= Side2),15,"GACC");
     pc_label(! (Side1 + Side2 <= Side3) && ! (Side2 + Side3 <= Side1 || 
                                               Side1 + Side3 <= Side2),16,
              "GACC");
     pc_label(Side2 + Side3 <= Side1 && ! (Side1 + Side2 <= Side3 || 
                                           Side1 + Side3 <= Side2),17,"GACC");
     pc_label(! (Side2 + Side3 <= Side1) && ! (Side1 + Side2 <= Side3 || 
                                               Side1 + Side3 <= Side2),18,
              "GACC");
     pc_label(Side1 + Side3 <= Side2 && ! (Side1 + Side2 <= Side3 || 
                                           Side2 + Side3 <= Side1),19,"GACC");
     pc_label(! (Side1 + Side3 <= Side2) && ! (Side1 + Side2 <= Side3 || 
                                               Side2 + Side3 <= Side1),20,
              "GACC");
     if ((Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2) 
       triOut = 4;
     else triOut = 1;
     __retres = triOut;
     goto return_label;
   }
   pc_label(triOut > 3,21,"GACC");
   pc_label(! (triOut > 3),22,"GACC");
   if (triOut > 3) triOut = 3;
   else {
     pc_label(triOut == 1 && Side1 + Side2 > Side3,23,"GACC");
     pc_label(! (triOut == 1) && Side1 + Side2 > Side3,24,"GACC");
     pc_label(Side1 + Side2 > Side3 && triOut == 1,25,"GACC");
     pc_label(! (Side1 + Side2 > Side3) && triOut == 1,26,"GACC");
     if (triOut == 1 && Side1 + Side2 > Side3) triOut = 2;
     else {
       pc_label(triOut == 2 && Side1 + Side3 > Side2,27,"GACC");
       pc_label(! (triOut == 2) && Side1 + Side3 > Side2,28,"GACC");
       pc_label(Side1 + Side3 > Side2 && triOut == 2,29,"GACC");
       pc_label(! (Side1 + Side3 > Side2) && triOut == 2,30,"GACC");
       if (triOut == 2 && Side1 + Side3 > Side2) triOut = 2;
       else {
         pc_label(triOut == 3 && Side2 + Side3 > Side1,31,"GACC");
         pc_label(! (triOut == 3) && Side2 + Side3 > Side1,32,"GACC");
         pc_label(Side2 + Side3 > Side1 && triOut == 3,33,"GACC");
         pc_label(! (Side2 + Side3 > Side1) && triOut == 3,34,"GACC");
         if (triOut == 3 && Side2 + Side3 > Side1) triOut = 2;
         else triOut = 4;
       }
     }
   }
   __retres = triOut;
   return_label: return __retres;
 }


