/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif

int triang(int Side1, int Side2, int Side3)
 {
   int __retres;
   int triOut;
   pc_label(Side1 <= 0 && ! (Side2 <= 0 || Side3 <= 0),1,"RACC",2,"cA1",
            Side2 <= 0,"cA2",Side3 <= 0);
   pc_label(! (Side1 <= 0) && ! (Side2 <= 0 || Side3 <= 0),2,"RACC",2,"cB1",
            Side2 <= 0,"cB2",Side3 <= 0);
   pc_label(Side2 <= 0 && ! (Side1 <= 0 || Side3 <= 0),3,"RACC",2,"cA1",
            Side1 <= 0,"cA2",Side3 <= 0);
   pc_label(! (Side2 <= 0) && ! (Side1 <= 0 || Side3 <= 0),4,"RACC",2,"cB1",
            Side1 <= 0,"cB2",Side3 <= 0);
   pc_label(Side3 <= 0 && ! (Side1 <= 0 || Side2 <= 0),5,"RACC",2,"cA1",
            Side1 <= 0,"cA2",Side2 <= 0);
   pc_label(! (Side3 <= 0) && ! (Side1 <= 0 || Side2 <= 0),6,"RACC",2,"cB1",
            Side1 <= 0,"cB2",Side2 <= 0);
   if ((Side1 <= 0 || Side2 <= 0) || Side3 <= 0) {
     triOut = 4;
     __retres = triOut;
     goto return_label;
   }
   triOut = 0;
   pc_label(Side1 == Side2,7,"RACC",0);
   pc_label(! (Side1 == Side2),8,"RACC",0);
   if (Side1 == Side2) triOut ++;
   pc_label(Side1 == Side3,9,"RACC",0);
   pc_label(! (Side1 == Side3),10,"RACC",0);
   if (Side1 == Side3) triOut += 2;
   pc_label(Side2 == Side3,11,"RACC",0);
   pc_label(! (Side2 == Side3),12,"RACC",0);
   if (Side2 == Side3) triOut += 3;
   pc_label(triOut == 0,13,"RACC",0);
   pc_label(! (triOut == 0),14,"RACC",0);
   if (triOut == 0) {
     pc_label(Side1 + Side2 <= Side3 && ! (Side2 + Side3 <= Side1 || 
                                           Side1 + Side3 <= Side2),15,"RACC",
              2,"cA1",Side2 + Side3 <= Side1,"cA2",Side1 + Side3 <= Side2);
     pc_label(! (Side1 + Side2 <= Side3) && ! (Side2 + Side3 <= Side1 || 
                                               Side1 + Side3 <= Side2),16,
              "RACC",2,"cB1",Side2 + Side3 <= Side1,"cB2",
              Side1 + Side3 <= Side2);
     pc_label(Side2 + Side3 <= Side1 && ! (Side1 + Side2 <= Side3 || 
                                           Side1 + Side3 <= Side2),17,"RACC",
              2,"cA1",Side1 + Side2 <= Side3,"cA2",Side1 + Side3 <= Side2);
     pc_label(! (Side2 + Side3 <= Side1) && ! (Side1 + Side2 <= Side3 || 
                                               Side1 + Side3 <= Side2),18,
              "RACC",2,"cB1",Side1 + Side2 <= Side3,"cB2",
              Side1 + Side3 <= Side2);
     pc_label(Side1 + Side3 <= Side2 && ! (Side1 + Side2 <= Side3 || 
                                           Side2 + Side3 <= Side1),19,"RACC",
              2,"cA1",Side1 + Side2 <= Side3,"cA2",Side2 + Side3 <= Side1);
     pc_label(! (Side1 + Side3 <= Side2) && ! (Side1 + Side2 <= Side3 || 
                                               Side2 + Side3 <= Side1),20,
              "RACC",2,"cB1",Side1 + Side2 <= Side3,"cB2",
              Side2 + Side3 <= Side1);
     if ((Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2) 
       triOut = 4;
     else triOut = 1;
     __retres = triOut;
     goto return_label;
   }
   pc_label(triOut > 3,21,"RACC",0);
   pc_label(! (triOut > 3),22,"RACC",0);
   if (triOut > 3) triOut = 3;
   else {
     pc_label(triOut == 1 && Side1 + Side2 > Side3,23,"RACC",1,"cA1",
              Side1 + Side2 > Side3);
     pc_label(! (triOut == 1) && Side1 + Side2 > Side3,24,"RACC",1,"cB1",
              Side1 + Side2 > Side3);
     pc_label(Side1 + Side2 > Side3 && triOut == 1,25,"RACC",1,"cA1",
              triOut == 1);
     pc_label(! (Side1 + Side2 > Side3) && triOut == 1,26,"RACC",1,"cB1",
              triOut == 1);
     if (triOut == 1 && Side1 + Side2 > Side3) triOut = 2;
     else {
       pc_label(triOut == 2 && Side1 + Side3 > Side2,27,"RACC",1,"cA1",
                Side1 + Side3 > Side2);
       pc_label(! (triOut == 2) && Side1 + Side3 > Side2,28,"RACC",1,"cB1",
                Side1 + Side3 > Side2);
       pc_label(Side1 + Side3 > Side2 && triOut == 2,29,"RACC",1,"cA1",
                triOut == 2);
       pc_label(! (Side1 + Side3 > Side2) && triOut == 2,30,"RACC",1,"cB1",
                triOut == 2);
       if (triOut == 2 && Side1 + Side3 > Side2) triOut = 2;
       else {
         pc_label(triOut == 3 && Side2 + Side3 > Side1,31,"RACC",1,"cA1",
                  Side2 + Side3 > Side1);
         pc_label(! (triOut == 3) && Side2 + Side3 > Side1,32,"RACC",1,"cB1",
                  Side2 + Side3 > Side1);
         pc_label(Side2 + Side3 > Side1 && triOut == 3,33,"RACC",1,"cA1",
                  triOut == 3);
         pc_label(! (Side2 + Side3 > Side1) && triOut == 3,34,"RACC",1,"cB1",
                  triOut == 3);
         if (triOut == 3 && Side2 + Side3 > Side1) triOut = 2;
         else triOut = 4;
       }
     }
   }
   __retres = triOut;
   return_label: return __retres;
 }


