/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif

int triang(int Side1, int Side2, int Side3)
 {
   int __retres;
   int triOut;
   pc_label(Side1 <= 0 && ! (Side2 <= 0 || Side3 <= 0),1,"CACC",1,"pa",
            (Side1 <= 0 || Side2 <= 0) || Side3 <= 0);
   pc_label(! (Side1 <= 0) && ! (Side2 <= 0 || Side3 <= 0),2,"CACC",1,"pb",
            (Side1 <= 0 || Side2 <= 0) || Side3 <= 0);
   pc_label(Side2 <= 0 && ! (Side1 <= 0 || Side3 <= 0),3,"CACC",1,"pa",
            (Side1 <= 0 || Side2 <= 0) || Side3 <= 0);
   pc_label(! (Side2 <= 0) && ! (Side1 <= 0 || Side3 <= 0),4,"CACC",1,"pb",
            (Side1 <= 0 || Side2 <= 0) || Side3 <= 0);
   pc_label(Side3 <= 0 && ! (Side1 <= 0 || Side2 <= 0),5,"CACC",1,"pa",
            (Side1 <= 0 || Side2 <= 0) || Side3 <= 0);
   pc_label(! (Side3 <= 0) && ! (Side1 <= 0 || Side2 <= 0),6,"CACC",1,"pb",
            (Side1 <= 0 || Side2 <= 0) || Side3 <= 0);
   if ((Side1 <= 0 || Side2 <= 0) || Side3 <= 0) {
     triOut = 4;
     __retres = triOut;
     goto return_label;
   }
   triOut = 0;
   pc_label(Side1 == Side2,7,"CACC",1,"pa",Side1 == Side2);
   pc_label(! (Side1 == Side2),8,"CACC",1,"pb",Side1 == Side2);
   if (Side1 == Side2) triOut ++;
   pc_label(Side1 == Side3,9,"CACC",1,"pa",Side1 == Side3);
   pc_label(! (Side1 == Side3),10,"CACC",1,"pb",Side1 == Side3);
   if (Side1 == Side3) triOut += 2;
   pc_label(Side2 == Side3,11,"CACC",1,"pa",Side2 == Side3);
   pc_label(! (Side2 == Side3),12,"CACC",1,"pb",Side2 == Side3);
   if (Side2 == Side3) triOut += 3;
   pc_label(triOut == 0,13,"CACC",1,"pa",triOut == 0);
   pc_label(! (triOut == 0),14,"CACC",1,"pb",triOut == 0);
   if (triOut == 0) {
     pc_label(Side1 + Side2 <= Side3 && ! (Side2 + Side3 <= Side1 || 
                                           Side1 + Side3 <= Side2),15,"CACC",
              1,"pa",
              (Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2);
     pc_label(! (Side1 + Side2 <= Side3) && ! (Side2 + Side3 <= Side1 || 
                                               Side1 + Side3 <= Side2),16,
              "CACC",1,"pb",
              (Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2);
     pc_label(Side2 + Side3 <= Side1 && ! (Side1 + Side2 <= Side3 || 
                                           Side1 + Side3 <= Side2),17,"CACC",
              1,"pa",
              (Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2);
     pc_label(! (Side2 + Side3 <= Side1) && ! (Side1 + Side2 <= Side3 || 
                                               Side1 + Side3 <= Side2),18,
              "CACC",1,"pb",
              (Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2);
     pc_label(Side1 + Side3 <= Side2 && ! (Side1 + Side2 <= Side3 || 
                                           Side2 + Side3 <= Side1),19,"CACC",
              1,"pa",
              (Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2);
     pc_label(! (Side1 + Side3 <= Side2) && ! (Side1 + Side2 <= Side3 || 
                                               Side2 + Side3 <= Side1),20,
              "CACC",1,"pb",
              (Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2);
     if ((Side1 + Side2 <= Side3 || Side2 + Side3 <= Side1) || Side1 + Side3 <= Side2) 
       triOut = 4;
     else triOut = 1;
     __retres = triOut;
     goto return_label;
   }
   pc_label(triOut > 3,21,"CACC",1,"pa",triOut > 3);
   pc_label(! (triOut > 3),22,"CACC",1,"pb",triOut > 3);
   if (triOut > 3) triOut = 3;
   else {
     pc_label(triOut == 1 && Side1 + Side2 > Side3,23,"CACC",1,"pa",
              triOut == 1 && Side1 + Side2 > Side3);
     pc_label(! (triOut == 1) && Side1 + Side2 > Side3,24,"CACC",1,"pb",
              triOut == 1 && Side1 + Side2 > Side3);
     pc_label(Side1 + Side2 > Side3 && triOut == 1,25,"CACC",1,"pa",
              triOut == 1 && Side1 + Side2 > Side3);
     pc_label(! (Side1 + Side2 > Side3) && triOut == 1,26,"CACC",1,"pb",
              triOut == 1 && Side1 + Side2 > Side3);
     if (triOut == 1 && Side1 + Side2 > Side3) triOut = 2;
     else {
       pc_label(triOut == 2 && Side1 + Side3 > Side2,27,"CACC",1,"pa",
                triOut == 2 && Side1 + Side3 > Side2);
       pc_label(! (triOut == 2) && Side1 + Side3 > Side2,28,"CACC",1,"pb",
                triOut == 2 && Side1 + Side3 > Side2);
       pc_label(Side1 + Side3 > Side2 && triOut == 2,29,"CACC",1,"pa",
                triOut == 2 && Side1 + Side3 > Side2);
       pc_label(! (Side1 + Side3 > Side2) && triOut == 2,30,"CACC",1,"pb",
                triOut == 2 && Side1 + Side3 > Side2);
       if (triOut == 2 && Side1 + Side3 > Side2) triOut = 2;
       else {
         pc_label(triOut == 3 && Side2 + Side3 > Side1,31,"CACC",1,"pa",
                  triOut == 3 && Side2 + Side3 > Side1);
         pc_label(! (triOut == 3) && Side2 + Side3 > Side1,32,"CACC",1,"pb",
                  triOut == 3 && Side2 + Side3 > Side1);
         pc_label(Side2 + Side3 > Side1 && triOut == 3,33,"CACC",1,"pa",
                  triOut == 3 && Side2 + Side3 > Side1);
         pc_label(! (Side2 + Side3 > Side1) && triOut == 3,34,"CACC",1,"pb",
                  triOut == 3 && Side2 + Side3 > Side1);
         if (triOut == 3 && Side2 + Side3 > Side1) triOut = 2;
         else triOut = 4;
       }
     }
   }
   __retres = triOut;
   return_label: return __retres;
 }


