/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

void donothing(void)
 {
   return;
 }

int maintest(int i)
{
  int __retres;
  pc_label_sequence(1,1UL,1,2,"137",0);
  while (1) pc_label_sequence_condition(0,"137");
  pc_label_sequence(1,1UL,2,2,"137",0);
  pc_label_sequence(1,2UL,1,2,"140",0);
  while (1) {
    pc_label_sequence_condition(0,"140");
    donothing();
  }
  pc_label_sequence(1,2UL,2,2,"140",0);
  pc_label_sequence(1,3UL,1,2,"142",0);
  while (1) {
    pc_label_sequence_condition(0,"142");
    if (! (i < 10)) break;
  }
  pc_label_sequence(1,3UL,2,2,"142",0);
  pc_label_sequence(1,4UL,1,2,"147",0);
  while (1) {
    if (i < 10) pc_label_sequence_condition(0,"147"); else break;
    donothing();
  }
  pc_label_sequence(1,4UL,2,2,"147",0);
  pc_label_sequence(1,5UL,1,2,"152",0);
  while (1) {
    int tmp;
    pc_label_sequence_condition(0,"152");
    tmp = i;
    i ++;
    ;
    if (! tmp) break;
  }
  pc_label_sequence(1,5UL,2,2,"152",0);
  pc_label_sequence(1,6UL,1,2,"160",0);
  while (1) {
    int tmp_0;
    tmp_0 = i;
    i ++;
    ;
    if (tmp_0) pc_label_sequence_condition(0,"160"); else break;
    donothing();
  }
  pc_label_sequence(1,6UL,2,2,"160",0);
  pc_label_sequence(1,7UL,1,2,"168",0);
  while (1) pc_label_sequence_condition(0,"168");
  pc_label_sequence(1,7UL,2,2,"168",0);
  pc_label_sequence(1,8UL,1,2,"170",0);
  while (1) {
    pc_label_sequence_condition(0,"170");
    donothing();
  }
  pc_label_sequence(1,8UL,2,2,"170",0);
  pc_label_sequence(1,9UL,1,2,"172",0);
  while (1) {
    pc_label_sequence_condition(0,"172");
    if (! (i < 10)) break;
  }
  pc_label_sequence(1,9UL,2,2,"172",0);
  pc_label_sequence(1,10UL,1,2,"178",0);
  while (1) {
    pc_label_sequence_condition(0,"178");
    donothing();
    if (! (i < 10)) break;
  }
  pc_label_sequence(1,10UL,2,2,"178",0);
  pc_label_sequence(1,11UL,1,2,"184",0);
  while (1) {
    int tmp_1;
    pc_label_sequence_condition(0,"184");
    tmp_1 = i;
    i ++;
    ;
    if (! tmp_1) break;
  }
  pc_label_sequence(1,11UL,2,2,"184",0);
  pc_label_sequence(1,12UL,1,2,"193",0);
  while (1) {
    int tmp_2;
    pc_label_sequence_condition(0,"193");
    donothing();
    tmp_2 = i;
    i ++;
    ;
    if (! tmp_2) break;
  }
  pc_label_sequence(1,12UL,2,2,"193",0);
  __retres = 0;
  return __retres;
}


