/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int main(int a)
 {
   int __SEQ_STATUS_1 = 1;
   int __SEQ_STATUS_2 = 0;
   int __SEQ_STATUS_3 = 0;
   int __SEQ_STATUS_4 = 0;
   int __SEQ_STATUS_5 = 0;
   int __SEQ_STATUS_6 = 0;
   int __SEQ_STATUS_7 = 0;
   __SEQ_STATUS_1 = 0;
   __SEQ_STATUS_2 = 0;
   __SEQ_STATUS_3 = 0;
   __SEQ_STATUS_4 = 0;
   __SEQ_STATUS_5 = 0;
   __SEQ_STATUS_6 = 0;
   __SEQ_STATUS_7 = 0;
   a = 0;
   __SEQ_STATUS_2 = 1;
   __SEQ_STATUS_1 = 0;
   __SEQ_STATUS_2 = 0;
   __SEQ_STATUS_3 = 0;
   __SEQ_STATUS_4 = 0;
   __SEQ_STATUS_5 = 0;
   __SEQ_STATUS_6 = 0;
   __SEQ_STATUS_7 = 0;
   a = 1;
   __SEQ_STATUS_3 = 1;
   __SEQ_STATUS_1 = 0;
   __SEQ_STATUS_2 = 0;
   __SEQ_STATUS_3 = 0;
   __SEQ_STATUS_4 = 0;
   __SEQ_STATUS_5 = 0;
   __SEQ_STATUS_6 = 0;
   __SEQ_STATUS_7 = 0;
   a = 2;
   __SEQ_STATUS_4 = 1;
   __SEQ_STATUS_1 = 0;
   __SEQ_STATUS_2 = 0;
   __SEQ_STATUS_3 = 0;
   __SEQ_STATUS_4 = 0;
   __SEQ_STATUS_5 = 0;
   __SEQ_STATUS_6 = 0;
   __SEQ_STATUS_7 = 0;
   a = 3;
   __SEQ_STATUS_5 = 1;
   __SEQ_STATUS_1 = 0;
   __SEQ_STATUS_2 = 0;
   __SEQ_STATUS_3 = 0;
   __SEQ_STATUS_4 = 0;
   __SEQ_STATUS_5 = 0;
   __SEQ_STATUS_6 = 0;
   __SEQ_STATUS_7 = 0;
   a = 4;
   __SEQ_STATUS_6 = 1;
   __SEQ_STATUS_1 = 0;
   __SEQ_STATUS_2 = 0;
   __SEQ_STATUS_3 = 0;
   __SEQ_STATUS_4 = 0;
   __SEQ_STATUS_5 = 0;
   __SEQ_STATUS_6 = 0;
   __SEQ_STATUS_7 = 0;
   a = 5;
   __SEQ_STATUS_7 = 1;
   pc_label(__SEQ_STATUS_1 == 1,1,"AUC");
   pc_label(__SEQ_STATUS_2 == 1,2,"AUC");
   pc_label(__SEQ_STATUS_3 == 1,3,"AUC");
   pc_label(__SEQ_STATUS_4 == 1,4,"AUC");
   pc_label(__SEQ_STATUS_5 == 1,5,"AUC");
   pc_label(__SEQ_STATUS_6 == 1,6,"AUC");
   pc_label(__SEQ_STATUS_7 == 1,7,"AUC");
   return a;
 }


