/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

struct coord {
    int x ;
    int y ;
};
int f(int x, int y)
{
  int __retres;
  struct coord test;
  int __SEQ_STATUS_x_1 = 1;
  int __SEQ_STATUS_y_2 = 1;
  int __SEQ_STATUS_test_3 = 0;
  int __SEQ_STATUS_test_4 = 0;
  pc_label(__SEQ_STATUS_x_1 == 1,1,"AUC");
  test.x = x;
  __SEQ_STATUS_test_3 = 1;
  pc_label(__SEQ_STATUS_y_2 == 1,2,"AUC");
  test.y = y;
  __SEQ_STATUS_test_4 = 1;
  pc_label(__SEQ_STATUS_test_3 == 1,3,"AUC");
  pc_label(__SEQ_STATUS_test_4 == 1,4,"AUC");
  __retres = test.x + test.y;
  return __retres;
}


