/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int main(int a)
 {
   int __SEQ_STATUS_a_1 = 0;
   a = 0;
   a = 1;
   a = 2;
   a = 3;
   a = 4;
   a = 5;
   __SEQ_STATUS_a_1 = 1;
   pc_label(__SEQ_STATUS_a_1 == 1,1,"AUC");
   return a;
 }


