/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

void g(int x)
 {
   return;
 }

int j(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

void f(void)
{
  int x;
  int __SEQ_STATUS_x_1 = 0;
  int __SEQ_STATUS_x_2 = 0;
  int __SEQ_STATUS_x_3 = 0;
  int __SEQ_STATUS_x_4 = 0;
  x = 0;
  __SEQ_STATUS_x_1 = 1;
  __SEQ_STATUS_x_3 = 1;
  while (1) {
    pc_label(__SEQ_STATUS_x_1 == 1,1,"AUC");
    pc_label(__SEQ_STATUS_x_2 == 1,2,"AUC");
    if (! (x < 10)) break;
    pc_label(__SEQ_STATUS_x_3 == 1,3,"AUC");
    pc_label(__SEQ_STATUS_x_4 == 1,4,"AUC");
    g(x);
    g(x);
    __SEQ_STATUS_x_1 = 0;
    __SEQ_STATUS_x_2 = 0;
    __SEQ_STATUS_x_3 = 0;
    __SEQ_STATUS_x_4 = 0;
    x ++;
    __SEQ_STATUS_x_2 = 1;
    __SEQ_STATUS_x_4 = 1;
  }
  return;
}


