/* Generated by Frama-C LTest */

#include "errno.h"
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"

#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int main(char *line)
 {
   int __retres;
   int i;
   int j;
   int __SEQ_STATUS_line_1 = 1;
   int __SEQ_STATUS_i_2 = 0;
   int __SEQ_STATUS_i_3 = 0;
   int __SEQ_STATUS_line_4 = 1;
   int __SEQ_STATUS_i_5 = 0;
   int __SEQ_STATUS_i_6 = 0;
   int __SEQ_STATUS_i_7 = 0;
   int __SEQ_STATUS_i_8 = 0;
   int __SEQ_STATUS_line_9 = 1;
   int __SEQ_STATUS_j_10 = 0;
   int __SEQ_STATUS_j_11 = 0;
   int __SEQ_STATUS_line_12 = 1;
   int __SEQ_STATUS_j_13 = 0;
   int __SEQ_STATUS_j_14 = 0;
   i = 0;
   __SEQ_STATUS_i_2 = 1;
   __SEQ_STATUS_i_5 = 1;
   __SEQ_STATUS_i_7 = 1;
   while (1) {
     pc_label(__SEQ_STATUS_line_1 == 1,1,"DUC");
     pc_label(__SEQ_STATUS_i_2 == 1,2,"DUC");
     pc_label(__SEQ_STATUS_i_3 == 1,3,"DUC");
     if (! ((int)*(line + i) != '\000')) break;
     while (1) {
       pc_label(__SEQ_STATUS_line_4 == 1,4,"DUC");
       pc_label(__SEQ_STATUS_i_5 == 1,5,"DUC");
       pc_label(__SEQ_STATUS_i_6 == 1,6,"DUC");
       if (! (! (((int)*(line + i) >= 'a' && (int)*(line + i) <= 'z' || 
                  (int)*(line + i) >= 'A' && (int)*(line + i) <= 'Z') || 
                 (int)*(line + i) == '\000'))) break;
       pc_label(__SEQ_STATUS_i_7 == 1,7,"DUC");
       pc_label(__SEQ_STATUS_i_8 == 1,8,"DUC");
       __SEQ_STATUS_j_10 = 0;
       __SEQ_STATUS_j_11 = 0;
       __SEQ_STATUS_j_13 = 0;
       __SEQ_STATUS_j_14 = 0;
       j = i;
       __SEQ_STATUS_j_10 = 1;
       __SEQ_STATUS_j_13 = 1;
       while (1) {
         pc_label(__SEQ_STATUS_line_9 == 1,9,"DUC");
         pc_label(__SEQ_STATUS_j_10 == 1,10,"DUC");
         pc_label(__SEQ_STATUS_j_11 == 1,11,"DUC");
         if (! ((int)*(line + j) != '\000')) break;
         pc_label(__SEQ_STATUS_line_12 == 1,12,"DUC");
         pc_label(__SEQ_STATUS_j_13 == 1,13,"DUC");
         pc_label(__SEQ_STATUS_j_14 == 1,14,"DUC");
         *(line + j) = *(line + (j + 1));
         __SEQ_STATUS_j_10 = 0;
         __SEQ_STATUS_j_11 = 0;
         __SEQ_STATUS_j_13 = 0;
         __SEQ_STATUS_j_14 = 0;
         j ++;
         __SEQ_STATUS_j_11 = 1;
         __SEQ_STATUS_j_14 = 1;
       }
       *(line + j) = (char)'\000';
     }
     __SEQ_STATUS_i_2 = 0;
     __SEQ_STATUS_i_3 = 0;
     __SEQ_STATUS_i_5 = 0;
     __SEQ_STATUS_i_6 = 0;
     __SEQ_STATUS_i_7 = 0;
     __SEQ_STATUS_i_8 = 0;
     i ++;
     __SEQ_STATUS_i_3 = 1;
     __SEQ_STATUS_i_6 = 1;
     __SEQ_STATUS_i_8 = 1;
   }
   printf("Output String: ");
   puts((char const *)line);
   __retres = 0;
   return __retres;
 }


