/* Generated by Frama-C LTest */

#include "errno.h"
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"

#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

int main(char *line)
 {
   int __retres;
   int i;
   int j;
   int __SEQ_STATUS_line_1 = 1;
   int __SEQ_STATUS_i_2 = 0;
   int __SEQ_TMP_i_2 = 0;
   int __SEQ_STATUS_i_3 = 0;
   int __SEQ_STATUS_line_4 = 1;
   int __SEQ_STATUS_i_5 = 0;
   int __SEQ_STATUS_i_6 = 0;
   int __SEQ_STATUS_i_7 = 0;
   int __SEQ_STATUS_i_8 = 0;
   int __SEQ_STATUS_line_9 = 1;
   int __SEQ_STATUS_j_10 = 0;
   int __SEQ_TMP_j_10 = 0;
   int __SEQ_STATUS_j_11 = 0;
   int __SEQ_STATUS_j_12 = 0;
   int __SEQ_TMP_j_12 = 0;
   int __SEQ_STATUS_j_13 = 0;
   int __SEQ_STATUS_line_14 = 1;
   int __SEQ_STATUS_j_15 = 0;
   int __SEQ_STATUS_j_16 = 0;
   int __SEQ_STATUS_j_17 = 0;
   int __SEQ_STATUS_j_18 = 0;
   i = 0;
   while (1) {
     pc_label(__SEQ_STATUS_line_1 == 1,1,"BDUC");
     pc_label(__SEQ_STATUS_i_2 == 1 && __SEQ_TMP_i_2 == (-2147483647-1),2,
              "BDUC");
     pc_label(__SEQ_STATUS_i_3 == 1 && __SEQ_TMP_i_2 == 2147483647,3,"BDUC");
     if (! ((int)*(line + i) != '\000')) break;
     while (1) {
       pc_label(__SEQ_STATUS_line_4 == 1,4,"BDUC");
       pc_label(__SEQ_STATUS_i_5 == 1 && __SEQ_TMP_i_2 == (-2147483647-1),5,
                "BDUC");
       pc_label(__SEQ_STATUS_i_6 == 1 && __SEQ_TMP_i_2 == 2147483647,6,
                "BDUC");
       if (! (! (((int)*(line + i) >= 'a' && (int)*(line + i) <= 'z' || 
                  (int)*(line + i) >= 'A' && (int)*(line + i) <= 'Z') || 
                 (int)*(line + i) == '\000'))) break;
       pc_label(__SEQ_STATUS_i_7 == 1 && __SEQ_TMP_i_2 == (-2147483647-1),7,
                "BDUC");
       pc_label(__SEQ_STATUS_i_8 == 1 && __SEQ_TMP_i_2 == 2147483647,8,
                "BDUC");
       __SEQ_STATUS_j_10 = 0;
       __SEQ_STATUS_j_11 = 0;
       __SEQ_STATUS_j_12 = 0;
       __SEQ_STATUS_j_13 = 0;
       __SEQ_STATUS_j_15 = 0;
       __SEQ_STATUS_j_16 = 0;
       __SEQ_STATUS_j_17 = 0;
       __SEQ_STATUS_j_18 = 0;
       j = i;
       __SEQ_STATUS_j_10 = 1;
       __SEQ_TMP_j_10 = j;
       __SEQ_STATUS_j_11 = 1;
       __SEQ_STATUS_j_15 = 1;
       __SEQ_STATUS_j_16 = 1;
       while (1) {
         pc_label(__SEQ_STATUS_line_9 == 1,9,"BDUC");
         pc_label(__SEQ_STATUS_j_10 == 1 && __SEQ_TMP_j_10 == (-2147483647-1),
                  10,"BDUC");
         pc_label(__SEQ_STATUS_j_11 == 1 && __SEQ_TMP_j_10 == 2147483647,11,
                  "BDUC");
         pc_label(__SEQ_STATUS_j_12 == 1 && __SEQ_TMP_j_12 == (-2147483647-1),
                  12,"BDUC");
         pc_label(__SEQ_STATUS_j_13 == 1 && __SEQ_TMP_j_12 == 2147483647,13,
                  "BDUC");
         if (! ((int)*(line + j) != '\000')) break;
         pc_label(__SEQ_STATUS_line_14 == 1,14,"BDUC");
         pc_label(__SEQ_STATUS_j_15 == 1 && __SEQ_TMP_j_10 == (-2147483647-1),
                  15,"BDUC");
         pc_label(__SEQ_STATUS_j_16 == 1 && __SEQ_TMP_j_10 == 2147483647,16,
                  "BDUC");
         pc_label(__SEQ_STATUS_j_17 == 1 && __SEQ_TMP_j_12 == (-2147483647-1),
                  17,"BDUC");
         pc_label(__SEQ_STATUS_j_18 == 1 && __SEQ_TMP_j_12 == 2147483647,18,
                  "BDUC");
         *(line + j) = *(line + (j + 1));
         __SEQ_STATUS_j_10 = 0;
         __SEQ_STATUS_j_11 = 0;
         __SEQ_STATUS_j_12 = 0;
         __SEQ_STATUS_j_13 = 0;
         __SEQ_STATUS_j_15 = 0;
         __SEQ_STATUS_j_16 = 0;
         __SEQ_STATUS_j_17 = 0;
         __SEQ_STATUS_j_18 = 0;
         j ++;
         __SEQ_STATUS_j_12 = 1;
         __SEQ_TMP_j_12 = j;
         __SEQ_STATUS_j_13 = 1;
         __SEQ_STATUS_j_17 = 1;
         __SEQ_STATUS_j_18 = 1;
       }
       *(line + j) = (char)'\000';
     }
     __SEQ_STATUS_i_2 = 0;
     __SEQ_STATUS_i_3 = 0;
     __SEQ_STATUS_i_5 = 0;
     __SEQ_STATUS_i_6 = 0;
     __SEQ_STATUS_i_7 = 0;
     __SEQ_STATUS_i_8 = 0;
     i ++;
     __SEQ_STATUS_i_2 = 1;
     __SEQ_TMP_i_2 = i;
     __SEQ_STATUS_i_3 = 1;
     __SEQ_STATUS_i_5 = 1;
     __SEQ_STATUS_i_6 = 1;
     __SEQ_STATUS_i_7 = 1;
     __SEQ_STATUS_i_8 = 1;
   }
   printf("Output String: ");
   puts((char const *)line);
   __retres = 0;
   return __retres;
 }


