/* Generated by Frama-C LTest */
#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif

extern int putchar(int c);

extern int printf(char const *x_0, int x_1);

extern void exit(int x);

int add(int x, int y)
{
  int __retres;
  __retres = x + y;
  return __retres;
}

int sub(int x, int y)
{
  int __retres;
  __retres = x - y;
  return __retres;
}

int mul(int x, int y)
{
  int __retres;
  int t;
  t = x * y;
  __retres = (t + 8192 / 2) / 8192;
  return __retres;
}

int div(int x, int y)
{
  int __retres;
  int t;
  t = x * 8192;
  __retres = (t + y / 2) / y;
  return __retres;
}

int of_int(int x)
{
  int __retres;
  __retres = x * 8192;
  return __retres;
}

int iter(int n, int a, int b, int xn, int yn)
{
  int __retres;
  int xn2;
  int yn2;
  int tmp;
  int tmp_0;
  int tmp_7;
  int tmp_4;
  int tmp_3;
  int tmp_1;
  int tmp_2;
  int tmp_6;
  int tmp_5;
  if (n == 100) {
    __retres = 1;
    goto return_label;
  }
  pc_label(1,1,"FCC");
  xn2 = mul(xn,xn);
  pc_label(1,2,"FCC");
  yn2 = mul(yn,yn);
  pc_label(1,3,"FCC");
  tmp = add(xn2,yn2);
  pc_label(1,4,"FCC");
  tmp_0 = of_int(4);
  if (tmp > tmp_0) {
    __retres = 0;
    goto return_label;
  }
  ;
  pc_label(1,5,"FCC");
  tmp_1 = mul(xn,yn);
  pc_label(1,6,"FCC");
  tmp_2 = of_int(2);
  pc_label(1,7,"FCC");
  tmp_3 = mul(tmp_2,tmp_1);
  pc_label(1,8,"FCC");
  tmp_4 = add(tmp_3,b);
  ;
  pc_label(1,9,"FCC");
  tmp_5 = sub(xn2,yn2);
  pc_label(1,10,"FCC");
  tmp_6 = add(tmp_5,a);
  ;
  ;
  ;
  pc_label(1,11,"FCC");
  tmp_7 = iter(n + 1,a,b,tmp_6,tmp_4);
  __retres = tmp_7;
  return_label: return __retres;
}

int inside(int x, int y)
{
  int tmp_1;
  int tmp;
  int tmp_0;
  pc_label(1,12,"FCC");
  tmp = of_int(0);
  pc_label(1,13,"FCC");
  tmp_0 = of_int(0);
  ;
  ;
  pc_label(1,14,"FCC");
  tmp_1 = iter(0,x,y,tmp_0,tmp);
  return tmp_1;
}

void run(int steps)
{
  int xmin;
  int xmax;
  int deltax;
  int ymin;
  int ymax;
  int deltay;
  int i;
  int tmp;
  int tmp_0;
  int tmp_1;
  int tmp_2;
  pc_label(1,15,"FCC");
  xmin = of_int(-2);
  pc_label(1,16,"FCC");
  xmax = of_int(1);
  pc_label(1,17,"FCC");
  tmp = of_int(2 * steps);
  pc_label(1,18,"FCC");
  tmp_0 = sub(xmax,xmin);
  pc_label(1,19,"FCC");
  deltax = div(tmp_0,tmp);
  pc_label(1,20,"FCC");
  ymin = of_int(-1);
  pc_label(1,21,"FCC");
  ymax = of_int(1);
  pc_label(1,22,"FCC");
  tmp_1 = of_int(steps);
  pc_label(1,23,"FCC");
  tmp_2 = sub(ymax,ymin);
  pc_label(1,24,"FCC");
  deltay = div(tmp_2,tmp_1);
  i = 0;
  while (i < steps) {
    {
      int y;
      int j;
      int tmp_4;
      int tmp_3;
      ;
      pc_label(1,25,"FCC");
      tmp_3 = of_int(i);
      pc_label(1,26,"FCC");
      tmp_4 = mul(tmp_3,deltay);
      ;
      pc_label(1,27,"FCC");
      y = add(ymin,tmp_4);
      j = 0;
      while (j < 2 * steps) {
        {
          int x;
          int r;
          int tmp_6;
          int tmp_5;
          ;
          pc_label(1,28,"FCC");
          tmp_5 = of_int(j);
          pc_label(1,29,"FCC");
          tmp_6 = mul(tmp_5,deltax);
          ;
          pc_label(1,30,"FCC");
          x = add(xmin,tmp_6);
          pc_label(1,31,"FCC");
          r = inside(x,y);
          if (r) {
            pc_label(1,32,"FCC");
            printf("%c",'0');
          }
          else {
            pc_label(1,33,"FCC");
            printf("%c",'1');
          }
        }
        j ++;
      }
      pc_label(1,34,"FCC");
      putchar('\n');
    }
    i ++;
  }
  return;
}

int main(void)
{
  int __retres;
  pc_label(1,35,"FCC");
  run(30);
  pc_label(1,36,"FCC");
  exit(0);
  __retres = 0;
  return __retres;
}


